language: c
sudo: required
env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin
    - GITHUB_OWNER=roswell
    - GITHUB_REPO=roswell-bin
os:
  - osx
  - linux

install:
  - sudo bash scripts/install.sh
  - chmod 755 /usr/local/bin/ros
  - ros setup
  - ros asdf install

before_script:
  - ros version
  - ros config
  - scripts/dispatch.sh
  - if [ x$TRAVIS_TAG != x ]; then scripts/dispatch.sh upload $TRAVIS_TAG; fi
  - if [ x$UPLOAD_TAG != x ]; then scripts/dispatch.sh upload $UPLOAD_TAG; fi

script:
  - echo "no test"

after_success:

