platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150916
  matrix:
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
    - MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32

install:
  - ps: If (Test-Path ("msys" + $env:MSYS2_BITS)){Write-Host "Using cached msys2"}
  - ps: If (-Not(Test-Path ("msys" + $env:MSYS2_BITS))){Invoke-WebRequest -UserAgent wget -Uri ("http://kent.dl.sourceforge.net/project/msys2/Base/" + $env:MSYS2_ARCH +  "/msys2-base-" + $env:MSYS2_ARCH + "-" + $env:MSYS2_BASEVER + ".tar.xz") -OutFile "msys2.tar.xz"}
  - ps: If (-Not(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar.xz}
  - ps: If (-Not(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar > $nul;&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc ("for i in {1..3}; do pacman --noconfirm -Suy autoconf automake mingw-w64-"+ $env:MSYS2_ARCH + "-gcc make zlib-devel python3 && break || sleep 15; done");&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "pacman --noconfirm -R -s bash-completion tftp-hpa inetutils util-linux tzcode time dash flex pax-git file bsdcpio bsdtar lndir";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "yes|pacman --noconfirm -Sc";&("msys" + $env:MSYS2_BITS + "\autorebase.bat");}

build_script:
  - # msys%MSYS2_BITS%\usr\bin\bash -lc "mkdir /tmp;cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; scripts/install.sh"
  - msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; scripts/dispatch.sh"
  - if NOT "%UPLOAD_TAG%" == "" msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; scripts/dispatch.sh upload $UPLOAD_TAG"
test_script:
  - which tar

artifacts:
  - path: roswell-bin-v0.0.6.64-MINGW32_NT-6.3-WOW.tgz
    name: roswell-bin-v0.0.6.64-MINGW32_NT-6.3-WOW.tgz
  - path: roswell-bin-v0.0.6.64-MINGW64_NT-6.3.tgz
    name: roswell-bin-v0.0.6.64-MINGW64_NT-6.3.tgz

